version: 2.1
orbs:
  architect: giantswarm/architect@dev:ce9a62fb6407cd537b3123a9546847b7b7fb0d0b

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
