version: 2.1
orbs:
  architect: giantswarm/architect@4.25.3

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
